
name: GitHub artifacts

on:
  workflow_dispatch:


jobs:
  uploadArtifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create artifact
        run: echo Hi > file.txt

      - uses: actions/upload-artifact@v3
        with:
          name: myArtifact
          path: file.txt

  downloadArtifact:
    needs: uploadArtifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: myArtifact

      - name: Show artifact
        run: cat file.txt

