
name: GitHub artifacts

on:
  workflow_dispatch:


jobs:
  uploadArtifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create artifact
        run: echo Hi > file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with: myArtifact 
          path: file.txt

  downloadArtifact:
    needs: uploadArtifact
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with: myArtifact 

      - name: Show artifact
        run: cat file.txt
