
name: Check what the GitHub Runner offers 

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check programms 
        run: |
          which curl
          which docker
          which wget
          which java
          which python
          which gibtesnicht
          /bin/true



