
name: Container for Job


on:
  workflow_dispatch:


jobs:

  container-job:

    runs-on: ubuntu-latest
    container:
      image: docker.io/debian:12
      env:
        HANS: PLUSKAL


    steps:
      - uses: actions/checkout@v4

      - name: Run commands in container 
        run: |
          echo === Print working directory ===
          pwd
          echo === List files and directories ===
          ls
          echo === Hostname ===
          hostname 
          echo === Show all environment variables ===
          env

