
name: Execute a shell script in Repo on GitHub Runner

on:
  workflow_dispatch

jobs:
  executeShellScript:
    runs-on: ubuntu-latest

    steps:
      - name: GIT checkout 
        uses: actions/checkout@v4

      - name: Execute shell script
        run: |
          chmod 700 ./myScript.sh
          ./myScript.sh
