
name: Execute a shell script in Repo on GitHub Runner

on:
  workflow_dispatch

jobs:
  executeShellScript:
    runs-on: ubuntu-latest

    steps:
      - name: Execute shell script
        run: ./myScript.sh
