
name: if syntax

on:
  workflow_dispatch

jobs:
  jobWithIfCondition:
    if: github.repository == 'bergwelten/MyTestRepository' 
    runs-on: ubuntu-latest

    steps:
      - name: Step if Job 
        run: echo "I am executed because job if condition is true."

  jobWithIfCondition:
    if: contains(github.repository, 'MyTestRepository')
    runs-on: ubuntu-latest

    steps:
      - name: Step if Job 2
        run: echo "I am executed because job if cindition is true."
