
name: Job dependency 

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Job 1
        run: echo "I am Job 1" 

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Job 2
        run: echo "I am Job 2"

