
name: Environment variables

on:
  workflow_dispatch:

env:
  GLOBAL_VAR: 'My global GitHub variable'

jobs:
  showGlobalVar:
    runs-on: ubuntu-latest

    steps:
      - name: Show my global variable 
        run: |
          echo $GLOBAL_VAR 
          echo ${{ env.GLOBAL_VAR }}

  showJobVar:
    runs-on: ubuntu-latest

    env:
      JOB_VAR: 'My Job variable'

    steps:
      - name: Show my Job variable
        run: echo $JOB_VAR

  showStepVar:
    runs-on: ubuntu-latest 

    steps:

      env:
        STEP_VAR: 'My Step variable'

      - name: Show my Step variable
        run: echo $STEP_VAR 

